
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
          docker pull ifedim/devtaskmaster:latest
          docker tag ifedim/devtaskmaster:latest ifedim/prodtaskmaster:latest
          docker push ifedim/prodtaskmaster:latest
    - name: Kubectl Action
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG_PROD }}
    - run: |
          kubectl apply -f deployment-service.yml
